name: Signalement de bug sur le site web
description: Signaler un bug pour nous aider à améliorer le site
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de nous aider à améliorer notre site web en fournissant les informations détaillées ci-dessous.
  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Fournissez une description claire et concise du bug.
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Navigateur
      description: Indiquez le navigateur web que vous utilisez.
    validations:
      required: true
  - type: input
    id: browser_version
    attributes:
      label: Version du navigateur
      description: Indiquez la version de votre navigateur web.
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Système d'exploitation
      description: Indiquez le système d'exploitation que vous utilisez.
    validations:
      required: true
  - type: input
    id: screen_resolution
    attributes:
      label: Résolution de l'écran
      description: Indiquez la résolution de votre écran.
    validations:
      required: true
  - type: input
    id: page_url
    attributes:
      label: URL de la page
      description: Indiquez l'URL de la page où vous avez rencontré le bug.
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Étapes pour reproduire le bug
      description: Fournissez une liste des étapes pour reproduire le bug.
    validations:
      required: true
